only: False
fps: 1000
max_ep_len: 600
horizon: 20
freq: 1
goal_ratio: 5

envs: 
  - 'MineDoJoPlainsAnimalsAndLogs-v2'
  - 'MineDoJoFlatAnimals-v1'
  - 'NewMineDoJoFlowerForest-v1'
  - 'Stone'

goals: 
  - 'log'
  - 'cow'
  - 'sheep'
  - 'pig'
  - "sheep"
  - "cow"
  - "pig"
  - "spider"
  - "polar_bear"
  - 'stone'

env_id:
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 3
