only: False
fps: 1000
max_ep_len: 600
horizon: 20
freq: 1
goal_ratio: 5
goals: 
  - "sheep"
  - "cow"
  - "pig"
  - "spider"
  - "polar_bear"
  - "chicken"
  - "horse"
  - "llama"
  - "mushroom_cow"

envs: 
  - 'MineDoJoPlainsAnimalsAndLogs-v2'
  - 'MineDoJoFlatAnimals-v1'
  - 'NewMineDoJoFlowerForest-v1'

env_id:  [1,1,1,1,1,1,1,1,1]